// examples/vite-svelte/src/App.svelte
<script lang="ts">
  import { wallet, director } from './wallet'
  import type {
    ParsedInviteCode,
    ParsedBolt11Invoice,
    PreviewFederation,
  } from '@fedimint/core'

  const TESTNET_FEDERATION_CODE =
    'fed11qgqrgvnhwden5te0v9k8q6rp9ekh2arfdeukuet595cr2ttpd3jhq6rzve6zuer9wchxvetyd938gcewvdhk6tcqqysptkuvknc7erjgf4em3zfh90kffqf9srujn6q53d6r056e4apze5cw27h75'

  // --- Wallet Status ---
  let isOpen = $state(false)
  let balance = $state(0)

  function checkIsOpen() {
    if (wallet) {
      isOpen = wallet.isOpen()
    }
  }

  $effect(() => {
    checkIsOpen()
    const unsubscribe = wallet?.balance.subscribeBalance((bal) => {
      checkIsOpen()
      balance = bal
    })
    return () => {
      unsubscribe?.()
    }
  })

  // --- Mnemonic Manager ---
  let mnemonicState = $state('')
  let inputMnemonic = $state('')
  let activeAction = $state<'get' | 'set' | 'generate' | null>(null)
  let mnemonicLoading = $state(false)
  let mnemonicMessage = $state<{
    text: string
    type: 'success' | 'error'
  } | null>(null)
  let showMnemonic = $state(false)

  function extractErrorMessage(error: any): string {
    let errorMsg = 'Operation failed'
    if (error instanceof Error) {
      errorMsg = error.message
    } else if (typeof error === 'object' && error !== null) {
      const rpcError = error as any
      if (rpcError.error) {
        errorMsg = rpcError.error
      } else if (rpcError.message) {
        errorMsg = rpcError.message
      }
    }
    return errorMsg
  }

  async function handleMnemonicAction(action: 'get' | 'set' | 'generate') {
    if (activeAction === action) {
      activeAction = null
      return
    }
    activeAction = action
    mnemonicMessage = null

    if (action === 'get') {
      await handleGetMnemonic()
    } else if (action === 'generate') {
      await handleGenerateMnemonic()
    }
  }

  async function handleGenerateMnemonic() {
    mnemonicLoading = true
    try {
      const newMnemonic = await director.generateMnemonic()
      mnemonicState = newMnemonic.join(' ')
      mnemonicMessage = { text: 'New mnemonic generated!', type: 'success' }
      showMnemonic = true
    } catch (error) {
      console.error('Error generating mnemonic:', error)
      mnemonicMessage = { text: extractErrorMessage(error), type: 'error' }
    } finally {
      mnemonicLoading = false
    }
  }

  async function handleGetMnemonic() {
    mnemonicLoading = true
    try {
      const mnemonic = await director.getMnemonic()
      if (mnemonic && mnemonic.length > 0) {
        mnemonicState = mnemonic.join(' ')
        mnemonicMessage = { text: 'Mnemonic retrieved!', type: 'success' }
        showMnemonic = true
      } else {
        mnemonicMessage = { text: 'No mnemonic found', type: 'error' }
      }
    } catch (error) {
      console.error('Error getting mnemonic:', error)
      mnemonicMessage = { text: extractErrorMessage(error), type: 'error' }
    } finally {
      mnemonicLoading = false
    }
  }

  async function handleSetMnemonic() {
    if (!inputMnemonic.trim()) return
    mnemonicLoading = true
    try {
      const words = inputMnemonic.trim().split(/\s+/)
      await director.setMnemonic(words)
      mnemonicMessage = { text: 'Mnemonic set successfully!', type: 'success' }
      inputMnemonic = ''
      mnemonicState = words.join(' ')
      activeAction = null
    } catch (error) {
      console.error('Error setting mnemonic:', error)
      mnemonicMessage = { text: extractErrorMessage(error), type: 'error' }
    } finally {
      mnemonicLoading = false
    }
  }

  async function copyMnemonicToClipboard() {
    try {
      await navigator.clipboard.writeText(mnemonicState)
      mnemonicMessage = { text: 'Copied to clipboard!', type: 'success' }
    } catch {
      mnemonicMessage = { text: 'Failed to copy', type: 'error' }
    }
  }

  // --- Join Federation ---
  let inviteCode = $state(TESTNET_FEDERATION_CODE)
  let joinResult = $state('')
  let joinError = $state('')
  let joining = $state(false)
  let previewData = $state<PreviewFederation | null>(null)
  let previewing = $state(false)

  async function previewFederation() {
    if (!inviteCode.trim()) return
    previewing = true
    joinError = ''
    try {
      previewData = await director.previewFederation(inviteCode)
      console.log('Preview federation:', previewData)
    } catch (e) {
      console.error('Error previewing federation:', e)
      joinError = e instanceof Error ? e.message : String(e)
      previewData = null
    } finally {
      previewing = false
    }
  }

  async function joinFederation() {
    checkIsOpen()
    console.log('Joining federation:', inviteCode)
    try {
      if (!wallet) throw new Error('Wallet unavailable')
      joining = true
      const res = await wallet.joinFederation(inviteCode)
      console.log('join federation res', res)
      joinResult = 'Joined!'
      joinError = ''
    } catch (e: any) {
      console.log('Error joining federation', e)
      joinError = typeof e === 'object' ? e.toString() : (e as string)
      joinResult = ''
    } finally {
      joining = false
    }
  }

  // --- Lightning Invoice ---
  let invoiceAmount = $state('')
  let invoiceDescription = $state('')
  let invoice = $state('')
  let invoiceError = $state('')
  let generating = $state(false)

  async function generateInvoice() {
    invoice = ''
    invoiceError = ''
    generating = true
    try {
      if (!wallet) throw new Error('Wallet unavailable')
      const response = await wallet.lightning.createInvoice(
        Number(invoiceAmount),
        invoiceDescription,
      )
      if (response) invoice = response.invoice
    } catch (e) {
      console.error('Error generating Lightning invoice', e)
      invoiceError = e instanceof Error ? e.message : String(e)
    } finally {
      generating = false
    }
  }

  // --- Redeem Ecash ---
  let ecashInput = $state('')
  let redeemResult = $state('')
  let redeemError = $state('')

  async function redeemEcash() {
    try {
      if (!wallet) throw new Error('Wallet unavailable')
      const res = await wallet.mint.redeemEcash(ecashInput)
      console.log('redeem ecash res', res)
      redeemResult = 'Redeemed!'
      redeemError = ''
    } catch (e) {
      console.log('Error redeeming ecash', e)
      redeemError = String(e)
      redeemResult = ''
    }
  }

  // --- Pay Lightning ---
  let lightningInput = $state('')
  let lightningResult = $state('')
  let lightningError = $state('')

  async function payLightning() {
    try {
      if (!wallet) throw new Error('Wallet unavailable')
      await wallet.lightning.payInvoice(lightningInput)
      lightningResult = 'Paid!'
      lightningError = ''
    } catch (e) {
      console.log('Error paying lightning', e)
      lightningError = String(e)
      lightningResult = ''
    }
  }

  // --- Parse Invite Code ---
  let parseInviteInput = $state('')
  let parseInviteResult = $state<ParsedInviteCode | null>(null)
  let parseInviteError = $state('')
  let parsingInvite = $state(false)

  async function parseInviteCode() {
    parseInviteResult = null
    parseInviteError = ''
    parsingInvite = true
    try {
      const result = await director.parseInviteCode(parseInviteInput)
      parseInviteResult = result
    } catch (e) {
      console.error('Error parsing invite code', e)
      parseInviteError = e instanceof Error ? e.message : String(e)
    } finally {
      parsingInvite = false
    }
  }

  // --- Parse Lightning Invoice ---
  let parseInvoiceInput = $state('')
  let parseInvoiceResult = $state<ParsedBolt11Invoice | null>(null)
  let parseInvoiceError = $state('')
  let parsingInvoice = $state(false)

  async function parseLightningInvoice() {
    parseInvoiceResult = null
    parseInvoiceError = ''
    parsingInvoice = true
    try {
      const result = await director.parseBolt11Invoice(parseInvoiceInput)
      console.log('result ', result)
      parseInvoiceResult = result
    } catch (e) {
      console.error('Error parsing invoice', e)
      parseInvoiceError = e instanceof Error ? e.message : String(e)
    } finally {
      parsingInvoice = false
    }
  }

  // --- Deposit ---
  let depositAddress = $state('')
  let addressError = $state('')
  let addressLoading = $state(false)

  async function generateAddress() {
    addressLoading = true
    try {
      if (!wallet) throw new Error('Wallet unavailable')
      const result = await wallet.wallet.generateAddress()
      if (result) depositAddress = result.deposit_address
    } catch (e) {
      console.error('Error', e)
      addressError = e instanceof Error ? e.message : String(e)
    } finally {
      addressLoading = false
    }
  }

  // --- Send Onchain ---
  let onchainAddress = $state('')
  let onchainAmount = $state(0)
  let onchainResult = $state('')
  let onchainError = $state('')
  let onchainLoading = $state(false)

  async function sendOnchain() {
    try {
      onchainLoading = true
      if (!wallet) throw new Error('Wallet unavailable')
      const result = await wallet.wallet.sendOnchain(
        onchainAmount,
        onchainAddress,
      )
      if (result) onchainResult = result.operation_id
    } catch (e) {
      console.error('Error ', e)
      onchainError = e instanceof Error ? e.message : String(e)
    } finally {
      onchainLoading = false
    }
  }
</script>

<header>
  <h1>Fedimint Typescript Library Demo</h1>

  <div class="steps">
    <strong>Steps to get started:</strong>
    <ol>
      <li>Join a Federation (persists across sessions)</li>
      <li>Generate an Invoice</li>
      <li>
        Pay the Invoice using the
        <a href="https://faucet.mutinynet.com/" target="_blank">
          mutinynet faucet
        </a>
      </li>
      <li>
        Investigate the Browser Tools
        <ul>
          <li>Browser Console for logs</li>
          <li>Network Tab (websocket) for guardian requests</li>
          <li>Application Tab for state</li>
        </ul>
      </li>
    </ol>
  </div>
</header>

<main>
  <!-- Wallet Status -->
  <div class="section">
    <h3>Wallet Status</h3>
    <div class="row">
      <strong>Is Wallet Open?</strong>
      <div>{isOpen ? 'Yes' : 'No'}</div>
      <button onclick={checkIsOpen}>Check</button>
    </div>
    <div class="row">
      <strong>Balance:</strong>
      <div class="balance">{balance}</div>
      sats
    </div>
  </div>

  <!-- Mnemonic Manager -->
  <div class="section mnemonic-section">
    <h3>🔑 Mnemonic Manager</h3>

    <div class="mnemonic-buttons">
      <button
        onclick={() => handleMnemonicAction('get')}
        disabled={mnemonicLoading}
        class="btn {activeAction === 'get' ? 'active' : ''}"
      >
        Get
      </button>
      <button
        onclick={() => handleMnemonicAction('set')}
        disabled={mnemonicLoading}
        class="btn {activeAction === 'set' ? 'active' : ''}"
      >
        Set
      </button>
      <button
        onclick={() => handleMnemonicAction('generate')}
        disabled={mnemonicLoading}
        class="btn {activeAction === 'generate' ? 'active' : ''}"
      >
        Generate
      </button>
    </div>

    {#if activeAction === 'set'}
      <form
        onsubmit={(e) => {
          e.preventDefault()
          handleSetMnemonic()
        }}
        class="mnemonic-form"
      >
        <textarea
          placeholder="Enter 12 or 24 words separated by spaces"
          bind:value={inputMnemonic}
          rows={2}
          class="mnemonic-input"
        ></textarea>
        <button
          type="submit"
          disabled={mnemonicLoading || !inputMnemonic.trim()}
          class="btn btn-primary"
        >
          {mnemonicLoading ? 'Setting...' : 'Set Mnemonic'}
        </button>
      </form>
    {/if}

    {#if mnemonicState}
      <div class="mnemonic-display">
        <div class="mnemonic-output">
          <span class={showMnemonic ? '' : 'blurred'}>
            {mnemonicState}
          </span>
          <div class="mnemonic-actions">
            <button
              onclick={() => (showMnemonic = !showMnemonic)}
              class="btn btn-small"
              title={showMnemonic ? 'Hide mnemonic' : 'Show mnemonic'}
            >
              {showMnemonic ? '👁️' : '👁️‍🗨️'}
            </button>
            <button
              onclick={copyMnemonicToClipboard}
              class="btn btn-small"
              disabled={!showMnemonic}
              title="Copy to clipboard"
            >
              📋
            </button>
          </div>
        </div>
      </div>
    {/if}

    {#if mnemonicMessage}
      <div class="message {mnemonicMessage.type}">{mnemonicMessage.text}</div>
    {/if}
  </div>

  <!-- Join Federation -->
  <div class="section">
    <h3>Join Federation</h3>
    <form
      onsubmit={(e) => {
        e.preventDefault()
        joinFederation()
      }}
      class="row"
    >
      <input
        class="ecash-input"
        placeholder="Invite Code..."
        required
        bind:value={inviteCode}
        disabled={isOpen}
      />
      <button
        type="button"
        onclick={previewFederation}
        disabled={previewing || !inviteCode.trim() || isOpen}
      >
        {previewing ? 'Previewing...' : 'Preview'}
      </button>
      <button type="submit" disabled={isOpen || joining}>
        {joining ? 'Joining...' : 'Join'}
      </button>
    </form>

    {#if previewData}
      <div class="preview-result">
        <h4>Federation Preview</h4>
        <div class="preview-info">
          <div>
            <strong>Federation ID:</strong>
            <code class="id">{previewData.federation_id}</code>
          </div>
          <div>
            <strong>Name:</strong>
            <span>
              {previewData.config.global.meta?.federation_name || 'Unnamed'}
            </span>
          </div>
          <div>
            <strong>Consensus Version:</strong>
            <span>
              {previewData.config.global.consensus_version.major}.{previewData
                .config.global.consensus_version.minor}
            </span>
          </div>
          <div>
            <strong>Guardians:</strong>
            <span>
              {Object.keys(previewData.config.global.api_endpoints).length}
            </span>
          </div>

          <details class="preview-details">
            <summary>Guardian Endpoints</summary>
            <div class="guardian-list">
              {#each Object.entries(previewData.config.global.api_endpoints) as [id, peer]}
                <div class="guardian-item">
                  <div><strong>{peer.name}</strong></div>
                  <div class="url">{peer.url}</div>
                </div>
              {/each}
            </div>
          </details>

          <details class="preview-details">
            <summary>Module Configuration</summary>
            <div class="module-list">
              {#each Object.entries(previewData.config.modules) as [id, mod]}
                <div class="module-item">
                  <strong>{mod.kind}</strong>
                </div>
              {/each}
            </div>
          </details>

          <details class="preview-details">
            <summary>Full JSON</summary>
            <pre>{JSON.stringify(previewData, null, 2)}</pre>
          </details>
        </div>
      </div>
    {/if}

    {#if !joinResult && isOpen}
      <i>(You've already joined a federation)</i>
    {/if}
    {#if joinResult}
      <div class="success">{joinResult}</div>
    {/if}
    {#if joinError}
      <div class="error">{joinError}</div>
    {/if}
  </div>

  <!-- Generate Lightning Invoice -->
  <div class="section">
    <h3>Generate Lightning Invoice</h3>
    <form
      onsubmit={(e) => {
        e.preventDefault()
        generateInvoice()
      }}
    >
      <div class="input-group">
        <label for="amount">Amount (msats):</label>
        <input
          id="amount"
          type="number"
          placeholder="Enter amount in msats"
          required
          bind:value={invoiceAmount}
        />
      </div>
      <div class="input-group">
        <label for="description">Description:</label>
        <input
          id="description"
          placeholder="Enter description"
          required
          bind:value={invoiceDescription}
        />
      </div>
      <button type="submit" disabled={generating}>
        {generating ? 'Generating...' : 'Generate Invoice'}
      </button>
    </form>
    <div>
      mutinynet faucet:{' '}
      <a href="https://faucet.mutinynet.com/" target="_blank">
        https://faucet.mutinynet.com/
      </a>
    </div>
    {#if invoice}
      <div class="success">
        <strong>Generated Invoice:</strong>
        <pre class="invoice-wrap">{invoice}</pre>
        <button onclick={() => navigator.clipboard.writeText(invoice)}>
          Copy
        </button>
      </div>
    {/if}
    {#if invoiceError}
      <div class="error">{invoiceError}</div>
    {/if}
  </div>

  <!-- Redeem Ecash -->
  <div class="section">
    <h3>Redeem Ecash</h3>
    <form
      onsubmit={(e) => {
        e.preventDefault()
        redeemEcash()
      }}
      class="row"
    >
      <input
        placeholder="Long ecash string..."
        required
        bind:value={ecashInput}
      />
      <button type="submit">redeem</button>
    </form>
    {#if redeemResult}
      <div class="success">{redeemResult}</div>
    {/if}
    {#if redeemError}
      <div class="error">{redeemError}</div>
    {/if}
  </div>

  <!-- Pay Lightning -->
  <div class="section">
    <h3>Pay Lightning</h3>
    <form
      onsubmit={(e) => {
        e.preventDefault()
        payLightning()
      }}
      class="row"
    >
      <input placeholder="lnbc..." required bind:value={lightningInput} />
      <button type="submit">pay</button>
    </form>
    {#if lightningResult}
      <div class="success">{lightningResult}</div>
    {/if}
    {#if lightningError}
      <div class="error">{lightningError}</div>
    {/if}
  </div>

  <!-- Parse Invite Code -->
  <div class="section">
    <h3>Parse Invite Code</h3>
    <form
      onsubmit={(e) => {
        e.preventDefault()
        parseInviteCode()
      }}
      class="row"
    >
      <input
        placeholder="Enter invite code..."
        bind:value={parseInviteInput}
        required
      />
      <button type="submit" disabled={parsingInvite}>
        {parsingInvite ? 'Parsing...' : 'Parse'}
      </button>
    </form>
    {#if parseInviteResult}
      <div class="success">
        <div class="row">
          <strong>Fed Id:</strong>
          <div class="id">{parseInviteResult.federation_id}</div>
        </div>
        <div class="row">
          <strong>Fed url:</strong>
          <div class="url">{parseInviteResult.url}</div>
        </div>
      </div>
    {/if}
    {#if parseInviteError}
      <div class="error">{parseInviteError}</div>
    {/if}
  </div>

  <!-- Parse Lightning Invoice -->
  <div class="section">
    <h3>Parse Lightning Invoice</h3>
    <form
      onsubmit={(e) => {
        e.preventDefault()
        parseLightningInvoice()
      }}
      class="row"
    >
      <input
        placeholder="Enter invoice..."
        bind:value={parseInvoiceInput}
        required
      />
      <button type="submit" disabled={parsingInvoice}>
        {parsingInvoice ? 'Parsing...' : 'Parse'}
      </button>
    </form>
    {#if parseInvoiceResult}
      <div class="success">
        <div class="row">
          <strong>Amount :</strong>
          <div class="id">{parseInvoiceResult.amount}</div>
          sats
        </div>
        <div class="row">
          <strong>Expiry :</strong>
          <div class="url">{parseInvoiceResult.expiry}</div>
        </div>
        <div class="row">
          <strong>Memo :</strong>
          <div class="url">{parseInvoiceResult.memo}</div>
        </div>
      </div>
    {/if}
    {#if parseInvoiceError}
      <div class="error">{parseInvoiceError}</div>
    {/if}
  </div>

  <!-- Generate Deposit Address -->
  <div class="section">
    <h3>Generate Deposit Address</h3>
    <form
      onsubmit={(e) => {
        e.preventDefault()
        generateAddress()
      }}
      class="row"
    >
      <button type="submit" disabled={addressLoading}>
        {addressLoading ? 'Generating...' : 'Generate'}
      </button>
    </form>
    {#if depositAddress}
      <div class="success">
        <p>{depositAddress}</p>
      </div>
    {/if}
    {#if addressError}
      <div class="error">{addressError}</div>
    {/if}
  </div>

  <!-- Send Onchain -->
  <div class="section">
    <h3>Send Onchain</h3>
    <form
      onsubmit={(e) => {
        e.preventDefault()
        sendOnchain()
      }}
      class="row"
    >
      <input
        placeholder="Enter amount"
        type="number"
        bind:value={onchainAmount}
        required
      />
      <input
        placeholder="Enter onchain address"
        bind:value={onchainAddress}
        required
      />
      <button type="submit" disabled={onchainLoading}>
        {onchainLoading ? 'Sending' : 'Send'}
      </button>
    </form>
    {#if onchainResult}
      <div class="success">
        <p>Onchain Send Successful</p>
      </div>
    {/if}
    {#if onchainError}
      <div class="error">{onchainError}</div>
    {/if}
  </div>
</main>

// examples/vite-core/src/App.tsx
import React, { useCallback, useEffect, useState } from 'react'
import { wallet, director } from './wallet'
import type {
  ParsedInviteCode,
  ParsedBolt11Invoice,
  PreviewFederation,
} from '@fedimint/core'

const TESTNET_FEDERATION_CODE =
  'fed11qgqrgvnhwden5te0v9k8q6rp9ekh2arfdeukuet595cr2ttpd3jhq6rzve6zuer9wchxvetyd938gcewvdhk6tcqqysptkuvknc7erjgf4em3zfh90kffqf9srujn6q53d6r056e4apze5cw27h75'

const useIsOpen = () => {
  const [open, setIsOpen] = useState(false)

  const checkIsOpen = useCallback(() => {
    if (wallet && open !== wallet?.isOpen()) {
      setIsOpen(wallet.isOpen())
    }
  }, [open])

  useEffect(() => {
    checkIsOpen()
  }, [checkIsOpen])

  return { open, checkIsOpen }
}

const useBalance = (checkIsOpen: () => void) => {
  const [balance, setBalance] = useState(0)

  useEffect(() => {
    const unsubscribe = wallet?.balance.subscribeBalance((balance) => {
      // checks if the wallet is open when the first
      // subscription event fires.
      // TODO: make a subscription to the wallet open status
      checkIsOpen()
      setBalance(balance)
    })

    return () => {
      unsubscribe?.()
    }
  }, [checkIsOpen])

  return balance
}

const App = () => {
  const { open, checkIsOpen } = useIsOpen()
  const balance = useBalance(checkIsOpen)

  return (
    <>
      <header>
        <h1>Fedimint Typescript Library Demo</h1>

        <div className="steps">
          <strong>Steps to get started:</strong>
          <ol>
            <li>Join a Federation (persists across sessions)</li>
            <li>Generate an Invoice</li>
            <li>
              Pay the Invoice using the{' '}
              <a href="https://faucet.mutinynet.com/" target="_blank">
                mutinynet faucet
              </a>
            </li>
            <li>
              Investigate the Browser Tools
              <ul>
                <li>Browser Console for logs</li>
                <li>Network Tab (websocket) for guardian requests</li>
                <li>Application Tab for state</li>
              </ul>
            </li>
          </ol>
        </div>
      </header>
      <main>
        <WalletStatus open={open} checkIsOpen={checkIsOpen} balance={balance} />
        <MnemonicManager />
        <JoinFederation open={open} checkIsOpen={checkIsOpen} />
        <GenerateLightningInvoice />
        <RedeemEcash />
        <SendLightning />
        <VerifyLightningAddress />
        <PayLightningAddress />
        <InviteCodeParser />
        <ParseLightningInvoice />
        <Deposit />
        <SendOnchain />
      </main>
    </>
  )
}

const MnemonicManager = () => {
  const [mnemonicState, setMnemonicState] = useState<string>('')
  const [inputMnemonic, setInputMnemonic] = useState<string>('')
  const [activeAction, setActiveAction] = useState<
    'get' | 'set' | 'generate' | null
  >(null)
  const [isLoading, setIsLoading] = useState(false)
  const [message, setMessage] = useState<{
    text: string
    type: 'success' | 'error'
  }>()
  const [showMnemonic, setShowMnemonic] = useState(false)

  const clearMessage = () => setMessage(undefined)

  // Helper function to extract user-friendly error messages
  const extractErrorMessage = (error: any): string => {
    let errorMsg = 'Operation failed'

    if (error instanceof Error) {
      errorMsg = error.message
    } else if (typeof error === 'object' && error !== null) {
      // Handle RPC error objects
      const rpcError = error as any
      if (rpcError.error) {
        errorMsg = rpcError.error
      } else if (rpcError.message) {
        errorMsg = rpcError.message
      }
    }

    return errorMsg
  }

  const handleAction = async (action: 'get' | 'set' | 'generate') => {
    if (activeAction === action) {
      setActiveAction(null)
      return
    }
    setActiveAction(action)
    clearMessage()

    if (action === 'get') {
      await handleGetMnemonic()
    } else if (action === 'generate') {
      await handleGenerateMnemonic()
    }
  }

  const handleGenerateMnemonic = async () => {
    setIsLoading(true)
    try {
      const newMnemonic = await director.generateMnemonic()
      setMnemonicState(newMnemonic.join(' '))
      setMessage({ text: 'New mnemonic generated!', type: 'success' })
      setShowMnemonic(true)
    } catch (error) {
      console.error('Error generating mnemonic:', error)
      const errorMsg = extractErrorMessage(error)
      setMessage({ text: errorMsg, type: 'error' })
    } finally {
      setIsLoading(false)
    }
  }

  const handleGetMnemonic = async () => {
    setIsLoading(true)
    try {
      const mnemonic = await director.getMnemonic()
      if (mnemonic && mnemonic.length > 0) {
        setMnemonicState(mnemonic.join(' '))
        setMessage({ text: 'Mnemonic retrieved!', type: 'success' })
        setShowMnemonic(true)
      } else {
        setMessage({ text: 'No mnemonic found', type: 'error' })
      }
    } catch (error) {
      console.error('Error getting mnemonic:', error)
      const errorMsg = extractErrorMessage(error)
      setMessage({ text: errorMsg, type: 'error' })
    } finally {
      setIsLoading(false)
    }
  }

  const handleSetMnemonic = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!inputMnemonic.trim()) return

    setIsLoading(true)
    try {
      const words = inputMnemonic.trim().split(/\s+/)
      await director.setMnemonic(words)
      setMessage({ text: 'Mnemonic set successfully!', type: 'success' })
      setInputMnemonic('')
      setMnemonicState(words.join(' '))
      setActiveAction(null)
    } catch (error) {
      console.error('Error setting mnemonic:', error)
      const errorMsg = extractErrorMessage(error)
      setMessage({ text: errorMsg, type: 'error' })
    } finally {
      setIsLoading(false)
    }
  }

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(mnemonicState)
      setMessage({ text: 'Copied to clipboard!', type: 'success' })
    } catch (error) {
      setMessage({ text: 'Failed to copy', type: 'error' })
    }
  }

  return (
    <div className="section mnemonic-section">
      <h3>🔑 Mnemonic Manager</h3>

      <div className="mnemonic-buttons">
        <button
          onClick={() => handleAction('get')}
          disabled={isLoading}
          className={`btn ${activeAction === 'get' ? 'active' : ''}`}
        >
          Get
        </button>
        <button
          onClick={() => handleAction('set')}
          disabled={isLoading}
          className={`btn ${activeAction === 'set' ? 'active' : ''}`}
        >
          Set
        </button>
        <button
          onClick={() => handleAction('generate')}
          disabled={isLoading}
          className={`btn ${activeAction === 'generate' ? 'active' : ''}`}
        >
          Generate
        </button>
      </div>

      {activeAction === 'set' && (
        <form onSubmit={handleSetMnemonic} className="mnemonic-form">
          <textarea
            placeholder="Enter 12 or 24 words separated by spaces"
            value={inputMnemonic}
            onChange={(e) => setInputMnemonic(e.target.value)}
            rows={2}
            className="mnemonic-input"
          />
          <button
            type="submit"
            disabled={isLoading || !inputMnemonic.trim()}
            className="btn btn-primary"
          >
            {isLoading ? 'Setting...' : 'Set Mnemonic'}
          </button>
        </form>
      )}

      {mnemonicState && (
        <div className="mnemonic-display">
          <div className="mnemonic-output">
            <span className={showMnemonic ? '' : 'blurred'}>
              {mnemonicState}
            </span>
            <div className="mnemonic-actions">
              <button
                onClick={() => setShowMnemonic(!showMnemonic)}
                className="btn btn-small"
                title={showMnemonic ? 'Hide mnemonic' : 'Show mnemonic'}
              >
                {showMnemonic ? '👁️' : '👁️‍🗨️'}
              </button>
              <button
                onClick={copyToClipboard}
                className="btn btn-small"
                disabled={!showMnemonic}
                title="Copy to clipboard"
              >
                📋
              </button>
            </div>
          </div>
        </div>
      )}

      {message && (
        <div className={`message ${message.type}`}>{message.text}</div>
      )}
    </div>
  )
}

const WalletStatus = ({
  open,
  checkIsOpen,
  balance,
}: {
  open: boolean
  checkIsOpen: () => void
  balance: number
}) => {
  return (
    <div className="section">
      <h3>Wallet Status</h3>
      <div className="row">
        <strong>Is Wallet Open?</strong>
        <div>{open ? 'Yes' : 'No'}</div>
        <button onClick={() => checkIsOpen()}>Check</button>
      </div>
      <div className="row">
        <strong>Balance:</strong>
        <div className="balance">{balance}</div>
        sats
      </div>
    </div>
  )
}

const JoinFederation = ({
  open,
  checkIsOpen,
}: {
  open: boolean
  checkIsOpen: () => void
}) => {
  const [inviteCode, setInviteCode] = useState(TESTNET_FEDERATION_CODE)
  const [previewData, setPreviewData] = useState<PreviewFederation | null>(null)
  const [previewing, setPreviewing] = useState(false)
  const [joinResult, setJoinResult] = useState<string | null>(null)
  const [joinError, setJoinError] = useState('')
  const [joining, setJoining] = useState(false)

  const previewFederationHandler = async () => {
    if (!inviteCode.trim()) return

    setPreviewing(true)
    setJoinError('')

    try {
      const data = await director.previewFederation(inviteCode)
      setPreviewData(data)
      console.log('Preview federation:', data)
    } catch (error) {
      console.error('Error previewing federation:', error)
      setJoinError(error instanceof Error ? error.message : String(error))
      setPreviewData(null)
    } finally {
      setPreviewing(false)
    }
  }

  const joinFederation = async (e: React.FormEvent) => {
    e.preventDefault()
    checkIsOpen()

    console.log('Joining federation:', inviteCode)
    try {
      if (!wallet) throw new Error('Wallet unavailable')
      setJoining(true)
      const res = await wallet.joinFederation(inviteCode)
      console.log('join federation res', res)
      setJoinResult('Joined!')
      setJoinError('')
    } catch (e: any) {
      console.log('Error joining federation', e)
      setJoinError(typeof e === 'object' ? e.toString() : (e as string))
      setJoinResult('')
    } finally {
      setJoining(false)
    }
  }

  return (
    <div className="section">
      <h3>Join Federation</h3>
      <form onSubmit={joinFederation} className="row">
        <input
          className="ecash-input"
          placeholder="Invite Code..."
          required
          value={inviteCode}
          onChange={(e) => {
            setInviteCode(e.target.value)
            setPreviewData(null)
          }}
          disabled={open}
        />
        <button
          type="button"
          onClick={previewFederationHandler}
          disabled={previewing || !inviteCode.trim() || open}
        >
          {previewing ? 'Previewing...' : 'Preview'}
        </button>
        <button type="submit" disabled={open || joining}>
          {joining ? 'Joining...' : 'Join'}
        </button>
      </form>

      {previewData && (
        <div className="preview-result">
          <h4>Federation Preview</h4>
          <div className="preview-info">
            <div className="preview-row">
              <strong>Federation ID:</strong>
              <code className="id">{previewData.federation_id}</code>
            </div>
            <div className="preview-row">
              <strong>Name:</strong>
              <span>
                {previewData.config.global.meta?.federation_name || 'Unnamed'}
              </span>
            </div>
            <div className="preview-row">
              <strong>Consensus Version:</strong>
              <span>
                {previewData.config.global.consensus_version.major}.
                {previewData.config.global.consensus_version.minor}
              </span>
            </div>
            <div className="preview-row">
              <strong>Guardians:</strong>
              <span>
                {Object.keys(previewData.config.global.api_endpoints).length}
              </span>
            </div>

            <details className="preview-details">
              <summary>Guardian Endpoints</summary>
              <div className="guardian-list">
                {Object.entries(previewData.config.global.api_endpoints).map(
                  ([id, peer]) => (
                    <div key={id} className="guardian-item">
                      <div>
                        <strong>{peer.name}</strong>
                      </div>
                      <div className="url">{peer.url}</div>
                    </div>
                  ),
                )}
              </div>
            </details>

            <details className="preview-details">
              <summary>Module Configuration</summary>
              <div className="module-list">
                {Object.entries(previewData.config.modules).map(
                  ([id, module]) => (
                    <div key={id} className="module-item">
                      <strong>{module.kind}</strong>
                    </div>
                  ),
                )}
              </div>
            </details>

            <details className="preview-details">
              <summary>Full JSON</summary>
              <pre>{JSON.stringify(previewData, null, 2)}</pre>
            </details>
          </div>
        </div>
      )}

      {!joinResult && open && <i>(You've already joined a federation)</i>}
      {joinResult && <div className="success">{joinResult}</div>}
      {joinError && <div className="error">{joinError}</div>}
    </div>
  )
}

const RedeemEcash = () => {
  const [ecashInput, setEcashInput] = useState('')
  const [redeemResult, setRedeemResult] = useState('')
  const [redeemError, setRedeemError] = useState('')

  const handleRedeem = async (e: React.FormEvent) => {
    e.preventDefault()
    try {
      if (!wallet) throw new Error('Wallet unavailable')
      const res = await wallet.mint.redeemEcash(ecashInput)
      console.log('redeem ecash res', res)
      setRedeemResult('Redeemed!')
      setRedeemError('')
    } catch (e) {
      console.log('Error redeeming ecash', e)
      setRedeemError(e as string)
      setRedeemResult('')
    }
  }

  return (
    <div className="section">
      <h3>Redeem Ecash</h3>
      <form onSubmit={handleRedeem} className="row">
        <input
          placeholder="Long ecash string..."
          required
          value={ecashInput}
          onChange={(e) => setEcashInput(e.target.value)}
        />
        <button type="submit">redeem</button>
      </form>
      {redeemResult && <div className="success">{redeemResult}</div>}
      {redeemError && <div className="error">{redeemError}</div>}
    </div>
  )
}

const SendLightning = () => {
  const [lightningInput, setLightningInput] = useState('')
  const [lightningResult, setLightningResult] = useState('')
  const [lightningError, setLightningError] = useState('')

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    try {
      if (!wallet) throw new Error('Wallet unavailable')
      await wallet.lightning.payInvoice(lightningInput)
      setLightningResult('Paid!')
      setLightningError('')
    } catch (e) {
      console.log('Error paying lightning', e)
      setLightningError(e as string)
      setLightningResult('')
    }
  }

  return (
    <div className="section">
      <h3>Pay Lightning</h3>
      <form onSubmit={handleSubmit} className="row">
        <input
          placeholder="lnbc..."
          required
          value={lightningInput}
          onChange={(e) => setLightningInput(e.target.value)}
        />
        <button type="submit">pay</button>
      </form>
      {lightningResult && <div className="success">{lightningResult}</div>}
      {lightningError && <div className="error">{lightningError}</div>}
    </div>
  )
}

const VerifyLightningAddress = () => {
  const [address, setAddress] = useState('')
  const [result, setResult] = useState('')
  const [error, setError] = useState('')

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setResult('')
    setError('')

    try {
      if (!wallet) throw new Error('Wallet unavailable')
      await director.verifyLightningAddress(address)
      setResult('Verified!')
    } catch (e) {
      console.error('Error verifying lightning address', e)
      setError('Failed!')
    }
  }

  return (
    <div className="section">
      <h3>Verify Lightning Address</h3>
      <form onSubmit={handleSubmit} className="row">
        <input
          placeholder="name@domain.com"
          required
          value={address}
          onChange={(e) => setAddress(e.target.value)}
        />
        <button type="submit">verify</button>
      </form>
      {result && <div className="success">{result}</div>}
      {error && <div className="error">{error}</div>}
    </div>
  )
}

const PayLightningAddress = () => {
  const [address, setAddress] = useState('')
  const [amountMsats, setAmountMsats] = useState('')
  const [result, setResult] = useState('')
  const [error, setError] = useState('')

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setResult('')
    setError('')

    try {
      if (!wallet) throw new Error('Wallet unavailable')
      await wallet.lightning.payLightningAddress(address, Number(amountMsats))

      setResult('Paid!')
    } catch (e) {
      console.error('Error paying lightning address', e)
      setError('Failed!')
    }
  }

  return (
    <div className="section">
      <h3>Pay Lightning Address</h3>
      <form onSubmit={handleSubmit} className="row">
        <input
          placeholder="name@domain.com"
          required
          value={address}
          onChange={(e) => setAddress(e.target.value)}
        />
        <input
          type="number"
          min="1"
          placeholder="Amount (msats)"
          required
          value={amountMsats}
          onChange={(e) => setAmountMsats(e.target.value)}
        />
        <button type="submit">pay</button>
      </form>
      {result && <div className="success">{result}</div>}
      {error && <div className="error">{error}</div>}
    </div>
  )
}

const GenerateLightningInvoice = () => {
  const [amount, setAmount] = useState('')
  const [description, setDescription] = useState('')
  const [invoice, setInvoice] = useState('')
  const [error, setError] = useState('')
  const [generating, setGenerating] = useState(false)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setInvoice('')
    setError('')
    setGenerating(true)
    try {
      if (!wallet) throw new Error('Wallet unavailable')
      const response = await wallet.lightning.createInvoice(
        Number(amount),
        description,
      )
      response && setInvoice(response.invoice)
    } catch (e) {
      console.error('Error generating Lightning invoice', e)
      setError(e instanceof Error ? e.message : String(e))
    } finally {
      setGenerating(false)
    }
  }

  return (
    <div className="section">
      <h3>Generate Lightning Invoice</h3>
      <form onSubmit={handleSubmit}>
        <div className="input-group">
          <label htmlFor="amount">Amount (msats):</label>
          <input
            id="amount"
            type="number"
            placeholder="Enter amount in msats"
            required
            value={amount}
            onChange={(e) => setAmount(e.target.value)}
          />
        </div>
        <div className="input-group">
          <label htmlFor="description">Description:</label>
          <input
            id="description"
            placeholder="Enter description"
            required
            value={description}
            onChange={(e) => setDescription(e.target.value)}
          />
        </div>
        <button type="submit" disabled={generating}>
          {generating ? 'Generating...' : 'Generate Invoice'}
        </button>
      </form>
      <div>
        mutinynet faucet:{' '}
        <a href="https://faucet.mutinynet.com/" target="_blank">
          https://faucet.mutinynet.com/
        </a>
      </div>
      {invoice && (
        <div className="success">
          <strong>Generated Invoice:</strong>
          <pre className="invoice-wrap">{invoice}</pre>
          <button onClick={() => navigator.clipboard.writeText(invoice)}>
            Copy
          </button>
        </div>
      )}
      {error && <div className="error">{error}</div>}
    </div>
  )
}

const InviteCodeParser = () => {
  const [inviteCode, setInviteCode] = useState('')
  const [parseResult, setParseResult] = useState<ParsedInviteCode | null>(null)
  const [parseError, setParseError] = useState('')
  const [parsingStatus, setParsingStatus] = useState(false)

  const handleParse = async (e: React.FormEvent) => {
    e.preventDefault()
    setParseResult(null)
    setParseError('')
    setParsingStatus(true)

    try {
      const result = await director.parseInviteCode(inviteCode)
      setParseResult(result)
    } catch (e) {
      console.error('Error parsing invite code', e)
      setParseError(e instanceof Error ? e.message : String(e))
    } finally {
      setParsingStatus(false)
    }
  }

  return (
    <div className="section">
      <h3>Parse Invite Code</h3>
      <form onSubmit={handleParse} className="row">
        <input
          placeholder="Enter invite code..."
          value={inviteCode}
          onChange={(e) => setInviteCode(e.target.value)}
          required
        />
        <button type="submit" disabled={parsingStatus}>
          {parsingStatus ? 'Parsing...' : 'Parse'}
        </button>
      </form>
      {parseResult && (
        <div className="success">
          <div className="row">
            <strong>Fed Id:</strong>
            <div className="id">{parseResult.federation_id}</div>
          </div>
          <div className="row">
            <strong>Fed url:</strong>
            <div className="url">{parseResult.url}</div>
          </div>
        </div>
      )}
      {parseError && <div className="error">{parseError}</div>}
    </div>
  )
}

const ParseLightningInvoice = () => {
  const [invoiceStr, setInvoiceStr] = useState('')
  const [parseResult, setParseResult] = useState<ParsedBolt11Invoice | null>(
    null,
  )
  const [parseError, setParseError] = useState('')
  const [parsingStatus, setParsingStatus] = useState(false)

  const handleParse = async (e: React.FormEvent) => {
    e.preventDefault()
    setParseResult(null)
    setParseError('')
    setParsingStatus(true)

    try {
      const result = await director.parseBolt11Invoice(invoiceStr)
      console.log('result ', result)
      setParseResult(result)
    } catch (e) {
      console.error('Error parsing invite code', e)
      setParseError(e instanceof Error ? e.message : String(e))
    } finally {
      setParsingStatus(false)
    }
  }

  return (
    <div className="section">
      <h3>Parse Lightning Invoice</h3>
      <form onSubmit={handleParse} className="row">
        <input
          placeholder="Enter invoice..."
          value={invoiceStr}
          onChange={(e) => setInvoiceStr(e.target.value)}
          required
        />
        <button type="submit" disabled={parsingStatus}>
          {parsingStatus ? 'Parsing...' : 'Parse'}
        </button>
      </form>
      {parseResult && (
        <div className="success">
          <div className="row">
            <strong>Amount :</strong>
            <div className="id">{parseResult.amount}</div>
            sats
          </div>
          <div className="row">
            <strong>Expiry :</strong>
            <div className="url">{parseResult.expiry}</div>
          </div>
          <div className="row">
            <strong>Memo :</strong>
            <div className="url">{parseResult.memo}</div>
          </div>
        </div>
      )}
      {parseError && <div className="error">{parseError}</div>}
    </div>
  )
}

const Deposit = () => {
  const [address, setAddress] = useState<string>('')
  const [addressError, setAddressError] = useState('')
  const [addressStatus, setAddressStatus] = useState(false)

  const handleGenerateAddress = async (e: React.FormEvent) => {
    e.preventDefault()
    setAddressStatus(true)
    try {
      if (!wallet) throw new Error('Wallet unavailable')
      const result = await wallet.wallet.generateAddress()
      result && setAddress(result.deposit_address)
    } catch (e) {
      console.error('Error', e)
      setAddressError(e instanceof Error ? e.message : String(e))
    } finally {
      setAddressStatus(false)
    }
  }
  return (
    <div className="section">
      <h3>Generate Deposit Address</h3>
      <form onSubmit={handleGenerateAddress} className="row">
        <button type="submit" disabled={addressStatus}>
          {addressStatus ? 'Generating...' : 'Generate'}
        </button>
      </form>
      {address && (
        <div className="success">
          <p>{address}</p>
        </div>
      )}
      {addressError && <div className="error">{addressError}</div>}
    </div>
  )
}

const SendOnchain = () => {
  const [address, setAddress] = useState('')
  const [amount, setAmount] = useState(0)
  const [withdrawalResult, setWithdrawalResult] = useState('')
  const [withdrawalError, setWithdrawalError] = useState('')
  const [withdrawalStatus, setWithdrawalStatus] = useState(false)

  const handleWithdraw = async (e: React.FormEvent) => {
    e.preventDefault()
    try {
      setWithdrawalStatus(true)
      if (!wallet) throw new Error('Wallet unavailable')
      const result = await wallet.wallet.sendOnchain(amount, address)
      result && setWithdrawalResult(result.operation_id)
    } catch (e) {
      console.error('Error ', e)
      setWithdrawalError(e instanceof Error ? e.message : String(e))
    } finally {
      setWithdrawalStatus(false)
    }
  }
  return (
    <div className="section">
      <h3>Send Onchain</h3>
      <form onSubmit={handleWithdraw} className="row">
        <input
          placeholder="Enter amount"
          type="number"
          value={amount}
          onChange={(e) => setAmount(Number(e.target.value))}
          required
        />
        <input
          placeholder="Enter onchain address"
          value={address}
          onChange={(e) => setAddress(e.target.value)}
          required
        />
        <button type="submit" disabled={withdrawalStatus}>
          {withdrawalStatus ? 'Sending' : 'Send'}
        </button>
      </form>
      {withdrawalResult && (
        <div className="success">
          <p>Onchain Send Successful</p>
        </div>
      )}
      {withdrawalError && <div className="error">{withdrawalError}</div>}
    </div>
  )
}

export default App
